#!/bin/sh

ffmpeg2theora -o "Coridoor medal_Start.ogg" "Coridoor medal_Start.mp4"
ffmpeg2theora -o "TestVideo_OneShot.ogg" "TestVideo_OneShot.mp4"
ffmpeg2theora -o "deathwheel.ogg" "deathwheel.mp4"
ffmpeg2theora -o "Coridoor medal_endloop.ogg" "Coridoor medal_endloop.mp4"
ffmpeg2theora -o "english dead.ogg" "english dead.mp4"
ffmpeg2theora -o "Coridoor time_endLoop.ogg" "Coridoor time_endLoop.mp4"
ffmpeg2theora -o "englishquestion_end.ogg" "englishquestion_end.mp4"
ffmpeg2theora -o "Coridoor time_start.ogg" "Coridoor time_start.mp4"
ffmpeg2theora -o "englishquestion_startLoop.ogg" "englishquestion_startLoop.mp4"
ffmpeg2theora -o "Coridoor_02_StartTrigger.ogg" "Coridoor_02_StartTrigger.mp4"
ffmpeg2theora -o "last coridorr_endLoop.ogg" "last coridorr_endLoop.mp4"
ffmpeg2theora -o "Coridoor_02_endLoop.ogg" "Coridoor_02_endLoop.mp4"
ffmpeg2theora -o "last coridorr_start.ogg" "last coridorr_start.mp4"
ffmpeg2theora -o "DeadRoom_01.ogg" "DeadRoom_01.mp4"
ffmpeg2theora -o "senses ending2_endloop.ogg" "senses ending2_endloop.mp4"
ffmpeg2theora -o "RedDead.ogg" "RedDead.mp4"
ffmpeg2theora -o "senses ending2_moo.ogg" "senses ending2_moo.mp4"
ffmpeg2theora -o "RedQuestion_end.ogg" "RedQuestion_end.mp4"
ffmpeg2theora -o "senses ending2_mooendloop.ogg" "senses ending2_mooendloop.mp4"
ffmpeg2theora -o "RedQuestion_startLoop.ogg" "RedQuestion_startLoop.mp4"
ffmpeg2theora -o "senses ending2_open your eyes.ogg" "senses ending2_open your eyes.mp4"
ffmpeg2theora -o "Room_01_StartLoop.ogg" "Room_01_StartLoop.mp4"
ffmpeg2theora -o "senses ending2_start.ogg" "senses ending2_start.mp4"
ffmpeg2theora -o "Room_01_Trigger.ogg" "Room_01_Trigger.mp4"
ffmpeg2theora -o "wheel_end.ogg" "wheel_end.mp4"
ffmpeg2theora -o "TestVideo_Loop.ogg" "TestVideo_Loop.mp4"
ffmpeg2theora -o "wheel_startloop.ogg" "wheel_startloop.mp4"